export const constants = {
  MOTOGP_BASE_URL: "https://racingmike.com/api/v1.0/",
  ENPOINTS: {
    SEASONS: "motogp-season",
    STANDING_RIDERS: "motogp-world-standing-riders",
    EVENTS: "motogp-events",
    FULL_RESULTS: "motogp-full-results",
  },
  TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
  MOTOGP_CATEGORY_ID: "e8c110ad-64aa-4e8e-8a86-f2f152f6a942",
  ridersObject: [
    { name: "Francesco Bagnaia", data: [], race: "" },
    { name: "Jorge Martin", data: [] },
    { name: "Marco Bezzecchi", data: [] },
    { name: "Brad Binder", data: [] },
    { name: "Aleix Espargaro", data: [] },
    { name: "Johann Zarco", data: [] },
    { name: "Maverick Viñales", data: [] },
    { name: "Luca Marini", data: [] },
    { name: "Jack Miller", data: [] },
    { name: "Fabio Quartararo", data: [] },
    { name: "Alex Marquez", data: [] },
    { name: "Franco Morbidelli", data: [] },
    { name: "Miguel Oliveira", data: [] },
    { name: "Augusto Fernandez", data: [] },
    { name: "Marc Marquez", data: [] },
    { name: "Fabio Di Giannantonio", data: [] },
    { name: "Alex Rins", data: [] },
    { name: "Takaaki Nakagami", data: [] },
    { name: "Raul Fernandez", data: [] },
    { name: "Dani Pedrosa", data: [] },
    { name: "Enea Bastianini", data: [] },
    { name: "Joan Mir", data: [] },
    { name: "Pol Espargaro", data: [] },
    { name: "Lorenzo Savadori", data: [] },
    { name: "Jonas Folger", data: [] },
    { name: "Stefan Bradl", data: [] },
    { name: "Michele Pirro", data: [] },
    { name: "Danilo Petrucci", data: [] },
    { name: "Cal Crutchlow", data: [] },
    { name: "Iker Lecuona", data: [] },
  ],
};
